// <auto-generated />
namespace DentalSurgery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ToothInSurgeryAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ToothInSurgeryAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201806021304035_ToothInSurgeryAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
